title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 You can update description in update blog details page.

baseurl: "/justinetestt" # the subpath of your site, e.g. /blog
url: "https://justinechacko.github.io" # the base hostname & protocol for your site
twitter_username: twitter

markdown: kramdown

name: Your awesome title

date: 2018-03-09 10:43:44 +0000
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more-->
sass:
    load_paths:
        - _sass
        - bs
logo: false
paginate: 10
paginate_path: "page:num"
adsid: ca-pub-8582082279264878
domain_name: https://justinechacko.github.io/justinetestt/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 
# Details for the RSS feed generator
author:        justinetestt
